# CloudCannon Global Configuration
# https://cloudcannon.com/documentation/articles/setting-global-configuration/

# Pass the author data file through to CloudCannon
data_config:
  authors: true

# Alternatively, to pass all data files:
# data_config: true

_inputs:
  author:
    type: select
    options:
      values: data.authors
