# CloudCannon Global Configuration
# https://cloudcannon.com/documentation/articles/setting-global-configuration/

collections_config:
  docs:
    name: Documentation
    path: content/docs
    schemas:
      default:
        path: schemas/doc.md
        _inputs:
          title:
            comment: The title for this page
          date:
            type: datetime
