# CloudCannon Global Configuration
# https://cloudcannon.com/documentation/articles/setting-global-configuration/

_inputs:
  related_items:
    type: multiselect
    options:
      values: collections.docs
      value_key: content_path