commit_templates:
  - label: Commit message with Ref
    template_string: 'Ref #{gitlab_ref}: {message|trim}'
    _inputs:
      message:
        comment: This comment will be shown above the input when users save changes
  - label: Custom commit message
    template_string: '{message|trim}'
    _inputs:
      message:
        comment: This comment will be shown above the input when users save changes